//Session
export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

//ADS
export const ADS_LOADED_REQUEST = 'ADS_LOADED_REQUEST';
export const ADS_LOADED_SUCCESS = 'ADS_LOADED_SUCCESS';
export const ADS_LOADED_FAILURE = 'ADS_LOADED_FAILURE';

//AD
export const AD_LOADED_REQUEST = 'AD_LOADED_REQUEST';
export const AD_LOADED_SUCCESS = 'AD_LOADED_SUCCESS';
export const AD_LOADED_FAILURE = 'AD_LOADED_FAILURE';

export const AD_CREATED_SUCCESS = 'AD_CREATED_SUCCESS';
export const AD_CREATED_FAILURE = 'AD_CREATED_FAILURE';

export const AD_DELETED_REQUEST = 'AD_DELETED_REQUEST';
export const AD_DELETED_SUCCESS = 'AD_DELETED_SUCCESS';
export const AD_DELETED_FAILURE = 'AD_DELETED_FAILURE';

//UI
export const UI_RESET_ERROR = 'UI_RESET_ERROR';
