//Session
export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

//Ads
export const ADS_LOADED_SUCCESS = 'ADS_LOADED_SUCCESS';
export const AD_LOADED_SUCCESS = 'AD_LOADED_SUCCESS';
export const AD_CREATED_SUCCESS = 'AD_CREATED_SUCCESS';

//Interface
export const UI_RESET_ERROR = 'UI_RESET_ERROR';
